version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    user: ${CURRENT_UID}
    container_name: web
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - .:/var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
      - PMA_ARBITRARY=1
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025
    restart: always
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - 7700:7700
    restart: always
    volumes:
      - meilisearch:/data.ms
  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: mercure
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      JWT_KEY: '!TheSecretToChange!'
      MERCURE_PUBLISHER_JWT_KEY: '!TheSecretToChange!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!TheSecretToChange!'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "8082:80"
      - "4433:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
  mysql:
  meilisearch:
