version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    user: ${CURRENT_UID}
    container_name: web
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - .:/var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
      - PMA_ARBITRARY=1
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025
    restart: always
volumes:
  mysql: